### ISSUE TITLE
Maybe we need these constants

### ISSUE THREAD

**Issue by wetalk** [Krielkip/mysql_PHP7#2]
!defined ('MYSQL_CLIENT_COMPRESS') && define ('MYSQL_CLIENT_COMPRESS', 32);
!defined ('MYSQL_CLIENT_IGNORE_SPACE') && define ('MYSQL_CLIENT_IGNORE_SPACE', 256);
!defined ('MYSQL_CLIENT_INTERACTIVE') && define ('MYSQL_CLIENT_INTERACTIVE', 1024);
!defined ('MYSQL_CLIENT_SSL') && define ('MYSQL_CLIENT_SSL', 2048);
!defined ('MYSQL_ASSOC') && define ('MYSQL_ASSOC', 1);
!defined ('MYSQL_BOTH') && define ('MYSQL_BOTH', 3);
!defined ('MYSQL_NUM') && define ('MYSQL_NUM', 2);

**Comment by Krielkip** [comment]
I've added these in this upload. Thanks for sharing.
